export interface Products {
    status:   boolean;
    products: Product[];
}

export interface Product {
  id:           number;
  barcode:      string;
  nombre:       string;
  costo_kilo:   number;
  stock_kilos:  number;
  proveedor_id: number;
  created_at:   string;
  updated_at:   string;
}

// Generated by https://quicktype.io

export interface GetProduct {
    status:  boolean;
    message: string;
    product: Producto;
}

export interface Producto {
  id:           number;
  barcode:      string;
  nombre:       string;
  costo_kilo:   number;
  stock_kilos:  number;
  proveedor_id: number;
  created_at:   string;
  updated_at:   string;
}
