// Generated by https://quicktype.io

export interface Tickets {
  status:  boolean;
  message: string;
  ticket:  Ticket[];
}

export interface Ticket {
  id:         number;
  tipo:       number;
  total:      number;
  usuario_id: number;
  created_at: string;
  updated_at: string;
}
