// Generated by https://quicktype.io

export interface Tickets {
  status:  boolean;
  message: string;
  ticket:  Ticket[];
}

export interface Ticket {
  id:         number;
  tipo:       number;
  total:      number;
  usuario_id: number;
  created_at: string;
  updated_at: string;
  usuario?: string;
}

// Generated by https://quicktype.io

export interface TicketDetails {
  status:  boolean;
  message: string;
  ticket:  Ticket;
  details: Detail[];
}

export interface Detail {
  id:          number;
  kilos:       number;
  costo_kilo:  number;
  subtotal:    number;
  total_cajas: number;
  total_tapas: number;
  ticket_id:   number;
  product_id:  number;
  created_at:  string;
  updated_at:  string;
  nombreProducto?: string;
}

export interface Ticket {
  id:         number;
  tipo:       number;
  total:      number;
  usuario_id: number;
  created_at: string;
  updated_at: string;
  tipoTK?:    string;
}
