// Generated by https://quicktype.io

export interface Usuarios {
    status:  boolean;
    usuario: Usuario[];
}

export interface Usuario {
    id:         number;
    nombre:     string;
    usuario:    string;
    created_at: string;
    updated_at: string;
}

// Generated by https://quicktype.io

export interface GetUsuario {
    status:  boolean;
    message: string;
    usuario: User;
}

export interface User {
    id:         number;
    nombre:     string;
    usuario:    string;
    created_at: string;
    updated_at: string;
}
